In [1]:
import numpy 
import sklearn

```java 
public class Car {
  // Fields (attributes)
  String color;
  int speed;

  // Constructor
  public Car(String carColor, int carSpeed) {
    this.color = carColor;
    this.speed = carSpeed;
  }

  // Method (behavior)
  public void drive() {
    System.out.println("The car is driving at " + speed + " mph.");
  }
  public void name(String Name){
      System.out.println("The Car is called " + Name +")
  }
}

Toyota = Car('red','80')
Toyota.drive()
 // Output: "The car is driving at 80 mph"
Toyota.name("Prius")
 // O : "The Car is called Prius"

```python 
 class Car:
    def __init__(carColor='black',carSpeed='40'):
        self.carColor = carColor
        self.speed = CarSpeed
    def drive():
        print(f'The car is driving at {speed} mph')
    def name(Name):
        print("The Car is called {Name}")

Toyota = Car('red','80')
Toyota.drive()
 // Output: "The car is driving at 80 mph"
Toyota.name("Prius")
 // O : "The Car is called Prius"



In [18]:
from sklearn.preprocessing import StandardScaler
class DataPreProcessing:
    def __init__(self,X,y):
        self.X = X
        self.y = y
    def standardization(self,X,y):
        scaler = StandardScaler()
        return scaler.fit_transform(X)
    def normalization(self,X,y):
        pass

    class DataCleaning:
        


In [20]:
import numpy as np
X = np.random.rand(100,10)
print(X.shape)
y = np.random.rand(100)
data = DataPreProcessing(X,y)
standard = data.standardization(X,y)
print(standard.shape)

(100, 10)
(100, 10)


In [8]:
import tensorflow as tf
import numpy as np

X_train = np.random.randn(1000, 5) * 10 + 3   # (N, features)
print(X_train)
norm = tf.keras.layers.Normalization(axis=-1)
print(norm)
adapt = norm.adapt(X_train)  # computes mean and variance on training set
print(adapt)
model = tf.keras.Sequential([
    tf.keras.Input(shape=(5,)),
    norm,
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer="adam", loss="mse")

[[  6.51935128   3.97569118  -3.25496629  -1.94844811   0.73354625]
 [ -8.39219657  -3.18953648 -14.84340106  -4.55395213  16.59585421]
 [ 15.54916162  -1.25003983   0.85476426  15.75242054  21.71844354]
 ...
 [ 20.45600742   5.84532952   8.84719684  -5.42445392 -11.83376275]
 [ 12.81261187  -3.63444188   9.20204221   0.55181282   0.17478892]
 [ 27.5421216   -3.22694055  -1.97084213   9.16340317  15.46772875]]
<Normalization name=normalization_3, built=False>
None


ValueError: None values not supported.